#!/bin/sh

BRANCH=$1
OLDCOMMIT=$2
NEWCOMMIT=$3

mustfail=0


CHANGED_FILES=$(git diff --name-only $OLDCOMMIT $NEWCOMMIT)

for file in $CHANGED_FILES; do
  zonename=`echo $(basename $file)| sed 's/.db//' | sed 's/^forward.//'`
  if [ "$zonename" = "" ]; then
    echo "$file cannot be parsed"
    mustfail=1
    continue
  fi

  temp=$(mktemp /tmp/zonec_XXXX)

  git show $NEWCOMMIT:$file >> $temp

  cat $temp | /usr/sbin/zonec -C -o $zonename -z -
  if [ $? -ne 0 ]; then
    mustfail=1
    echo "$zonename does not compile with zonec" >&2
  fi

  rm $temp
done

exit $mustfail
